version: 2.1

executors:
  lein:
    docker:
      - image: circleci/clojure:lein-2.9.3
    working_directory: ~/repo

orbs:
  node: circleci/node@1.1.6

jobs:
  deps:
    executor: lein
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: boonmee-{{ checksum "project.clj" }}

  test:
    executor: lein
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - node/install
      - run: npm install -g typescript
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - run: ./scripts/test

  compile_linux:
    executor: lein
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - run: ./scripts/compile

workflows:
  version: 2.1
  general_build:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - compile_linux:
          requires:
            - deps