version: 2.1

executors:
  lein:
    docker:
      - image: circleci/clojure:lein-2.9.3
    working_directory: ~/repo

orbs:
  node: circleci/node@1.1.6

jobs:
  deps:
    executor: lein
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: boonmee-{{ checksum "project.clj" }}

  test:
    executor: lein
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - node/install
      - run: sudo npm install -g typescript
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - run: ./scripts/test

  compile_macos:
    executor: macos
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /home/circleci/graalvm-ce-java11-darwin-amd64-20.1.0
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-20.1.0 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz
              tar xzf graalvm-ce-java11-darwin-amd64-20.1.0.tar.gz
            fi
      - run: ./scripts/compile
      - run:
          name: Release artifact
          command: |
            mkdir /tmp/release
            mv boonmee /tmp/release
      - store_artifacts:
          path: /tmp/release
          destination: release

  compile_linux:
    executor: lein
    working_directory: ~/repo
    environment:
      GRAALVM_HOME: /home/circleci/graalvm-ce-java11-20.1.0
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: boonmee-{{ checksum "project.clj" }}
      - restore_cache:
          keys:
            - linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc g++ zlib1g-dev
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-20.1.0 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
              tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
            fi
      - run: ./scripts/compile
      - run:
          name: Release artifact
          command: |
            mkdir /tmp/release
            mv boonmee /tmp/release
            sha256sum /tmp/release/boonmee
      - save_cache:
          paths:
            - ~/graalvm-ce-java11-20.1.0
          key: linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: /tmp/release
          destination: release

workflows:
  version: 2.1
  general_build:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - compile_linux:
          requires:
            - deps
      - compile_macos:
          requires:
            - deps