name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        lein deps
        sudo npm install -g typescript
    - name: Run tests
      run: ./scripts/test

  linux_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          lein deps
      - name: Install GraalVM
        run: |
          cd /tmp
          curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
      - name: Compile
        run: ./scripts/compile
        env: 
          GRAALVM_HOME: /tmp/graalvm-ce-java11-linux-amd64-20.1.0
        
