name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        lein deps
        sudo npm install -g typescript
    - name: Run tests
      run: ./scripts/test

  linux_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          lein deps
      - name: Compile
        run: |
          curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          ls -lh
          ls $GRAALVM_HOME
          echo $GRAALVM_HOME
          ./scripts/compile
        env: 
          GRAALVM_HOME: graalvm-ce-java11-linux-amd64-20.1.0
      - name: boonmee native image
        uses: actions/upload-artifact@v1
        with:
          name: boonmee-linux
          path: /tmp/boonmee
