name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        lein deps
        sudo npm install -g typescript
    - name: Run tests
      run: ./scripts/test

  linux_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: lein deps
      - name: Install GraalVM
        run: |
          curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
      - name: Compile
        run: ./scripts/compile
        env: 
          GRAALVM_HOME: graalvm-ce-java11-20.1.0
      - name: SHA
        run: sha256sum boonmee
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: boonmee-linux-1.0.0-alpha1
          path: boonmee

  macos_compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lein
        run: brew install leiningen
      - name: Install dependencies
        run: lein deps
      - name: Install GraalVM
        run: brew cask install graalvm/tap/graalvm-ce-lts-java11
      - name: Compile
        run: ./scripts/compile
        env:
          GRAALVM_HOME: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: boonmee-macos-1.0.0-alpha1
          path: boonmee