name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Version'
        required: true
        default: '0.1.0'

jobs:
  linux_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: lein deps
      - name: Install GraalVM
        run: |
          curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
          tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
      - name: Compile
        run: ./scripts/compile ${{ github.event.inputs.release }}
        env:
          GRAALVM_HOME: graalvm-ce-java11-20.1.0
      - name: SHA
        run: sha256sum boonmee
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: boonmee-linux-${{ github.event.inputs.release }}
          path: boonmee

  macos_compile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lein
        run: brew install leiningen
      - name: Install dependencies
        run: lein deps
      - name: Install GraalVM
        run: brew cask install graalvm/tap/graalvm-ce-java11
      - name: Compile
        run: ./scripts/compile ${{ github.event.inputs.release }}
        env:
          GRAALVM_HOME: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home
      - name: SHA
        run: shasum -a 256 boonmee
      - name: Artifact
        uses: actions/upload-artifact@v1
        with:
          name: boonmee-macos-${{ github.event.inputs.release }}
          path: boonmee